# Generated by Django 5.1.4 on 2024-12-24 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_name', models.CharField(max_length=100, unique=True)),
                ('car_desc', models.TextField(default='', max_length=500)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'permissions': [('can_edit_car', 'Can edit car details'), ('can_view_car', 'Can view car details')],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': [('can_view_customer', 'Can view customer details'), ('can_edit_customer', 'Can edit customer details')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('days_for_rent', models.PositiveIntegerField()),
                ('rental_date', models.DateField(auto_now_add=True)),
                ('loc_from', models.CharField(max_length=100)),
                ('loc_to', models.CharField(max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cars', models.ManyToManyField(related_name='orders', to='car_rental.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='car_rental.customer')),
            ],
            options={
                'permissions': [('can_view_order', 'Can view order details'), ('can_create_order', 'Can create new orders'), ('can_manage_order', 'Can manage and edit orders')],
            },
        ),
    ]
